# Generated by Django 5.2.17 on 2026-09-07 14:53

import django.db.models.deletion
import storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("work", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=storage.models.upload_path)),
                ("original_name", models.CharField(editable=False, max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private (me and administrators)"),
                            ("TEAM", "Team (everyone can see it)"),
                            ("ADMIN_ONLY", "Administrators only"),
                        ],
                        default="PRIVATE",
                        max_length=12,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="work.project",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="work.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_by", "-created_at"],
                        name="storage_upl_uploade_6f7b5e_idx",
                    )
                ],
            },
        ),
    ]
