# Generated by Django 5.2.17 on 2026-09-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("MEMBER_INVITED", "Member invited"),
                            ("MEMBER_ACTIVATED", "Member activated"),
                            ("MEMBER_UPDATED", "Member updated"),
                            ("MEMBER_DEACTIVATED", "Member deactivated"),
                            ("MEMBER_REACTIVATED", "Member reactivated"),
                            ("TASK_CREATED", "Task created"),
                            ("TASK_UPDATED", "Task updated"),
                            ("TASK_STATUS_CHANGED", "Task status changed"),
                            ("HOURS_ADDED", "Work hours added"),
                            ("HOURS_UPDATED", "Work hours edited"),
                            ("HOURS_DELETED", "Work hours deleted"),
                            ("FILE_UPLOADED", "File uploaded"),
                            ("FILE_DELETED", "File deleted"),
                            ("REPORT_SUBMITTED", "Daily report submitted"),
                            ("REPORT_UPDATED", "Daily report updated"),
                            ("FORM_STATS_RECORDED", "Form statistics recorded"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member this action concerns, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity log entry",
                "verbose_name_plural": "activity log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "-created_at"],
                        name="core_activi_subject_9e32fe_idx",
                    ),
                    models.Index(
                        fields=["verb", "-created_at"],
                        name="core_activi_verb_385a28_idx",
                    ),
                ],
            },
        ),
    ]
