# Generated by Django 5.2.17 on 2026-09-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(
                blank=True,
                help_text="Optional. Leave blank and the deadline is the end of that day.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Roughly how long this should take, e.g. 6 for 'finish in 6 hours'.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
