# Generated by Django 5.2.17 on 2026-09-08 03:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_task_due_time_task_estimated_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Roughly how long this should take, e.g. 6 for 'finish in 6 hours'.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.25")),
                    django.core.validators.MaxValueValidator(Decimal("999")),
                ],
            ),
        ),
    ]
