# Generated by Django 5.2.17 on 2026-09-07 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("work", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One line: what today was about.", max_length=255
                    ),
                ),
                ("work_completed", models.TextField(help_text="What you finished.")),
                (
                    "blockers",
                    models.TextField(
                        blank=True,
                        help_text="Anything stopping you. Leave blank if none.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_tasks",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="work.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "-date"],
                        name="reports_dai_member__c53b97_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "date"), name="one_report_per_member_per_day"
                    )
                ],
            },
        ),
    ]
