# Generated by Django 5.2.17 on 2026-09-07 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "google_form_id",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank until Google is connected. Statistics can still be entered by hand.",
                        max_length=120,
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(
                        blank=True,
                        help_text="The responses spreadsheet, once available.",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracked_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tracked form",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmissionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("submission_count", models.PositiveIntegerField(default=0)),
                (
                    "verified_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Of those submissions, how many have been checked.",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a row came from Google rather than by hand.",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="google_forms.trackedform",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("form", "date"), name="one_stat_per_form_per_day"
                    )
                ],
            },
        ),
    ]
