# Generated by Django 5.2.17 on 2026-09-08 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TASK_ASSIGNED", "New assignment"),
                            ("TASK_REASSIGNED", "Assignment moved to you"),
                            ("TASK_UPDATED", "Assignment updated"),
                            ("TASK_DUE_SOON", "Deadline approaching"),
                            ("HOURS_RECORDED", "Working hours recorded"),
                            ("GENERAL", "Notice"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Where clicking this notification goes.",
                        max_length=255,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an email was also sent for this.",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="notificatio_recipie_ce9d56_idx",
                    )
                ],
            },
        ),
    ]
