# Generated by Django 5.2.17 on 2026-09-08 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "start_source",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Signed in"),
                            ("MANUAL", "Started manually"),
                        ],
                        default="LOGIN",
                        max_length=10,
                    ),
                ),
                (
                    "end_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOGOUT", "Signed out"),
                            ("MANUAL", "Stopped manually"),
                            ("AUTO", "Closed automatically"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "auto_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Nobody signed out - this was closed at the daily cap, so the figure is not a real measurement.",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "-started_at"],
                        name="attendance__member__b7b87e_idx",
                    ),
                    models.Index(
                        fields=["ended_at"], name="attendance__ended_a_39f3ed_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="attendance_end_after_start",
                    )
                ],
            },
        ),
    ]
